version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
       - ./php/app:/app
       - ./php/app/vendor:/app/vendor
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db
    command: >
      sh -c "composer install && composer dump-autoload --optimize && php bin/console doctrine:migrations:migrate --no-interaction && php -S 0.0.0.0:8000 -t public"

  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    volumes:
      - ./front/app:/app
    depends_on:
      - php
    ports:
      - "3000:3000"
    networks:
      - app-network
    command: >
      sh -c "yarn install && npm start"

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: new_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:
  shared:

networks:
  app-network: